-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'EMPLOYEE');

CREATE TABLE "segments" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE
);

CREATE TABLE "families" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  "segmentId" INTEGER NOT NULL REFERENCES "segments"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(nombre, "segmentId")
);

CREATE TABLE "classes" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  "familyId" INTEGER NOT NULL REFERENCES "families"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(nombre, "familyId")
);

CREATE TABLE "bricks" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  "classId" INTEGER NOT NULL REFERENCES "classes"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(nombre, "classId")
);

CREATE TABLE "attributes" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  "brickId" INTEGER NOT NULL REFERENCES "bricks"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(nombre, "brickId")
);

CREATE TABLE "products" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10,2) NOT NULL,
  "brickId" INTEGER NOT NULL REFERENCES "bricks"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE "users" (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role "Role" NOT NULL DEFAULT 'EMPLOYEE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT NOW()
);
